In [1]:
%matplotlib inline
# %matplotlib notebook
from matplotlib import pyplot as plt

In [46]:

data = ((2+1)*18+4+4)*8
x = [9600, 19200, 57600, 115200, 1e6] # bits/sec
y = [data*1000/d for d in x]          # time to send packset (msec)
z = [1000/s for s in y]               # packets/sec (Hz or command rate)
# err = []
print(x)
print(y)
print(z)

plt.subplot(2,1,1); plt.plot(x,y,'b^', label="DR")
plt.grid(True)
plt.ylabel('msec/packet')
plt.subplot(2,1,2); plt.plot(x,z,'g^', label="Hz")
plt.grid(True);
plt.ylabel('Hz')
plt.xlabel('baud rate')

[9600, 19200, 57600, 115200, 1000000.0]
[51.666666666666664, 25.833333333333332, 8.61111111111111, 4.305555555555555, 0.496]
[19.35483870967742, 38.70967741935484, 116.12903225806453, 232.25806451612905, 2016.1290322580646]


Text(0.5, 0, 'baud rate')

In [47]:
import numpy as np
np.set_printoptions(precision=1)
np.set_printoptions(suppress=True)

In [48]:
tab = np.array([[x],[y],[z]]).T
print(tab)

[[[   9600.       51.7      19.4]]

 [[  19200.       25.8      38.7]]

 [[  57600.        8.6     116.1]]

 [[ 115200.        4.3     232.3]]

 [[1000000.        0.5    2016.1]]]


| Baud Rate|Transmit Packet (msec)| Command Rate (Hz) |
|---------|------|--------|
| 9600    | 51.7 | 19.4   |
| 19200   | 25.8 | 38.7   |
| 57600   | 8.6  | 116.1  |
| 115200  | 4.3  | 232.3  |
| 1000000 | 0.5  | 2016.1 |

In [49]:
1000/4.3

232.55813953488374